export {default as Home} from './home'
export {default as Privacy} from './privacy'
export {default as Faq} from './faq'
export {default as Blog} from  './blog';
export {default as Stayconnected} from './stayconnected';
export {default as Community} from './community';
export {default as Express} from './express';
export {default as HelixBusiness} from './helix-business';
export {default as Download} from './download';